// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class AuditLog
{
    public string Id { get; set; }

    public string EntityType { get; set; }

    public string ActionType { get; set; }

    public string UserId { get; set; }

    public DateTime? ChangeDate { get; set; }

    public string Changes { get; set; }
}