// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class EmployeeProjectAssignment
{
    public string Id { get; set; }

    public string EmployeeId { get; set; }

    public string ProjectId { get; set; }

    public DateTime? AssignedDate { get; set; }

    public DateTime? UnassignedDate { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Project Project { get; set; }
}