// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class EmployeeHistory
{
    public string Id { get; set; }

    public string EmployeeId { get; set; }

    public string PositionId { get; set; }

    public decimal? OldSalary { get; set; }

    public decimal? NewSalary { get; set; }

    public string ChangeReason { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Position Position { get; set; }
}