// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class EventLog
{
    public string Id { get; set; }

    public string Notes { get; set; }
   
    public sbyte? Frequency { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public sbyte? IsActive { get; set; }

    public virtual Employee AuthorizedByNavigation { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual EventType Event { get; set; }
}