// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class OverTime
{
    public string Id { get; set; }

    public string EmployeeId { get; set; }

    public int? DayOvertime { get; set; }

    public int? NightOvertime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? PeriodStart { get; set; }

    public DateTime? PeriodEnd { get; set; }

    public virtual Employee Employee { get; set; }
}