// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class PaymentHistory
{
    public string Id { get; set; }

    public string PayrollId { get; set; }

    public string EmployeeId { get; set; }

    public DateTime? PaymentDate { get; set; }

    public decimal? Amount { get; set; }

    public sbyte? Status { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Payroll Payroll { get; set; }
}