// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class PayrollDetail
{
    public string Id { get; set; }

    public string PayrollId { get; set; }

    public string EmployeeId { get; set; }

    public int? WorkedDays { get; set; }

    public decimal? SalaryBase { get; set; }

    public decimal? PerDay { get; set; }

    public decimal? DayOvertime { get; set; }

    public decimal? NightOvertime { get; set; }

    public decimal? SalaryOvertime { get; set; }

    public decimal? SubTotal { get; set; }

    public decimal? Bonus { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Earned { get; set; }

    public decimal? Isss { get; set; }

    public decimal? EmployeerIsss { get; set; }

    public decimal? Afp { get; set; }

    public decimal? EmployeerAfp { get; set; }

    public decimal? Isr { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? ToPay { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Payroll Payroll { get; set; }
}