// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class Position
{
    public string Id { get; set; }
    public sbyte? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<EmployeeHistory> EmployeeHistories { get; set; } = new List<EmployeeHistory>();

    public virtual OrganizationDepartment OrganizationDepartment { get; set; }
}