// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class Project
{
    public string Id { get; set; }

    public sbyte? IsActive { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<EmployeeProjectAssignment> EmployeeProjectAssignments { get; set; } = new List<EmployeeProjectAssignment>();

    public virtual Employee Manager { get; set; }
}