// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class QuotationType
{
    public string Id { get; set; }

    public string Name { get; set; }

    public decimal? EmployeePercentage { get; set; }

    public decimal? EmployerPercentage { get; set; }

    public sbyte? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedBy { get; set; }
}