// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaOrbita.Model.Models;

public partial class TaskExecutionLog
{
    public int Id { get; set; }

    public string TaskId { get; set; }

    public DateTime? ExecutionDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }
}